# 从 .config 生成 include/generated/config.h
# 在顶层 Makefile 中 include 此文件

CONFIG_H := $(WORK_DIR)/include/generated/config.h
KCONFIG  := $(WORK_DIR)/Kconfig
DOTCONFIG := $(WORK_DIR)/.config

$(CONFIG_H): $(DOTCONFIG)
	@mkdir -p $(dir $(CONFIG_H))
	@echo "/* Auto-generated by gen-config.mk — do not edit */" > $(CONFIG_H)
	@echo "#pragma once" >> $(CONFIG_H)
	@awk -F= '/^CONFIG_/ { \
	    key=$$1; val=$$2; \
	    gsub(/^[[:space:]]+|[[:space:]]+$$/,"",val); \
	    if (val=="y") { \
	        print "#define " key " 1"; \
	    } else if (val ~ /^".*"$$/) { \
	        gsub(/^"|"$$/,"",val); \
	        print "#define " key " \"" val "\""; \
	    } else if (val ~ /^[0-9]/ || val ~ /^0x/) { \
	        print "#define " key " " val; \
	    } \
	}' $(DOTCONFIG) >> $(CONFIG_H)
	@echo "  GEN     $(CONFIG_H)"

# 便捷目标
.PHONY: gen-config
gen-config: $(CONFIG_H)
